# -*- coding: utf-8 -*-
"""bert-lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wPfo-7k1P_rwarBaNlIzpD9MOz0VMRPT
"""

import collections
import numpy as np
import torch
from torch import nn
from datasets import load_dataset
from transformers import AutoTokenizer
import evaluate
from tqdm.auto import tqdm
from torch.utils.data import DataLoader
from transformers import AutoModelForQuestionAnswering

import argparse
import os
from datetime import datetime
import time
import random



def parse_args():
    parser = argparse.ArgumentParser(description="python training script")
    parser.add_argument("--lr", type=float, default=2e-5, help="learning rate")
    parser.add_argument("--epochs", type=int, default=1, help="number of epochs")
    parser.add_argument("--seed", type=int, default=42, help="random seed")
    parser.add_argument("--batch-size", type=int, default=8, help="batch size")
    parser.add_argument("--data-fraction", type=float, default=1.0, help="percentage of the dataset to use")
    parser.add_argument("--precision", type=str, default="fp32", choices=["fp32", "amp"])    
    parser.add_argument("--data-dir", type=str, default='./data', help="data directory")
    parser.add_argument("--ckpt-path", type=str, default='./checkpoint.pt', help="checkpoint path")
    return parser.parse_args()
args = parse_args()

random.seed(args.seed)
np.random.seed(args.seed)
torch.manual_seed(args.seed)
use_amp = args.precision == "amp"
scaler = torch.amp.GradScaler("cuda", enabled=use_amp)

raw_datasets = load_dataset("rajpurkar/squad")

raw_datasets["train"] = raw_datasets["train"].select(range((int)(len(raw_datasets["train"]) * args.data_fraction)))
raw_datasets["validation"] = raw_datasets["validation"].select(range((int)(len(raw_datasets["validation"]) * args.data_fraction)))

print("train : ",len(raw_datasets["train"]))
print("validation : ",len(raw_datasets["validation"]))

device = "cuda" if(torch.cuda.is_available()) else "cpu"
print(device)

model_checkpoint = "google-bert/bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

max_length = 384
stride = 128


def preprocess_training_examples(examples):
    questions = [q.strip() for q in examples["question"]]
    inputs = tokenizer(
        questions,
        examples["context"],
        max_length=max_length,
        truncation="only_second",
        stride=stride,
        return_overflowing_tokens=True,
        return_offsets_mapping=True,
        padding="max_length",
    )

    offset_mapping = inputs.pop("offset_mapping")
    sample_map = inputs.pop("overflow_to_sample_mapping")
    answers = examples["answers"]
    start_positions = []
    end_positions = []

    for i, offset in enumerate(offset_mapping):
        sample_idx = sample_map[i]
        answer = answers[sample_idx]
        start_char = answer["answer_start"][0]
        end_char = answer["answer_start"][0] + len(answer["text"][0])
        sequence_ids = inputs.sequence_ids(i)

        # Find the start and end of the context
        idx = 0
        while sequence_ids[idx] != 1:
            idx += 1
        context_start = idx
        while sequence_ids[idx] == 1:
            idx += 1
        context_end = idx - 1

        # If the answer is not fully inside the context, label is (0, 0)
        if offset[context_start][0] > start_char or offset[context_end][1] < end_char:
            start_positions.append(0)
            end_positions.append(0)
        else:
            # Otherwise it's the start and end token positions
            idx = context_start
            while idx <= context_end and offset[idx][0] <= start_char:
                idx += 1
            start_positions.append(idx - 1)

            idx = context_end
            while idx >= context_start and offset[idx][1] >= end_char:
                idx -= 1
            end_positions.append(idx + 1)

    inputs["start_positions"] = start_positions
    inputs["end_positions"] = end_positions
    return inputs

train_dataset = raw_datasets["train"].map(
    preprocess_training_examples,
    batched=True,
    remove_columns=raw_datasets["train"].column_names,
)

def preprocess_validation_examples(examples):
    questions = [q.strip() for q in examples["question"]]
    inputs = tokenizer(
        questions,
        examples["context"],
        max_length=max_length,
        truncation="only_second",
        stride=stride,
        return_overflowing_tokens=True,
        return_offsets_mapping=True,
        padding="max_length",
    )

    sample_map = inputs.pop("overflow_to_sample_mapping")
    example_ids = []

    for i in range(len(inputs["input_ids"])):
        sample_idx = sample_map[i]
        example_ids.append(examples["id"][sample_idx])

        sequence_ids = inputs.sequence_ids(i)
        offset = inputs["offset_mapping"][i]
        inputs["offset_mapping"][i] = [
            o if sequence_ids[k] == 1 else None for k, o in enumerate(offset)
        ]

    inputs["example_id"] = example_ids
    return inputs

validation_dataset = raw_datasets["validation"].map(
    preprocess_validation_examples,
    batched=True,
    remove_columns=raw_datasets["validation"].column_names,
)

n_best = 20
max_answer_length= 30

metric = evaluate.load("squad")



def compute_metrics(start_logits, end_logits, features, examples):
    example_to_features = collections.defaultdict(list)
    for idx, feature in enumerate(features):
        example_to_features[feature["example_id"]].append(idx)

    predicted_answers = []
    for example in tqdm(examples):
        example_id = example["id"]
        context = example["context"]
        answers = []

        # Loop through all features associated with that example
        for feature_index in example_to_features[example_id]:
            start_logit = start_logits[feature_index]
            end_logit = end_logits[feature_index]
            offsets = features[feature_index]["offset_mapping"]

            start_indexes = np.argsort(start_logit)[-1 : -n_best - 1 : -1].tolist()
            end_indexes = np.argsort(end_logit)[-1 : -n_best - 1 : -1].tolist()
            for start_index in start_indexes:
                for end_index in end_indexes:
                    # Skip answers that are not fully in the context
                    if offsets[start_index] is None or offsets[end_index] is None:
                        continue
                    # Skip answers with a length that is either < 0 or > max_answer_length
                    if (
                        end_index < start_index
                        or end_index - start_index + 1 > max_answer_length
                    ):
                        continue

                    answer = {
                        "text": context[offsets[start_index][0] : offsets[end_index][1]],
                        "logit_score": start_logit[start_index] + end_logit[end_index],
                    }
                    answers.append(answer)

        # Select the answer with the best score
        if len(answers) > 0:
            best_answer = max(answers, key=lambda x: x["logit_score"])
            predicted_answers.append(
                {"id": example_id, "prediction_text": best_answer["text"]}
            )
        else:
            predicted_answers.append({"id": example_id, "prediction_text": ""})

    theoretical_answers = [{"id": ex["id"], "answers": ex["answers"]} for ex in examples]
    return metric.compute(predictions=predicted_answers, references=theoretical_answers)

train_dataset.set_format(
    type="torch")
processed_validation_dataset = validation_dataset.remove_columns(["example_id", "offset_mapping"])
processed_validation_dataset.set_format("torch")

train_loader = DataLoader(
    train_dataset,
    shuffle=True,             # shuffle for stochastic training
    batch_size=args.batch_size,
    pin_memory=True,          # speeds up GPU transfers
)

# Create DataLoader for model input
val_loader = DataLoader(
    processed_validation_dataset,
    shuffle=False,            # don't shuffle during validation
    batch_size=args.batch_size,
    pin_memory=True,
)

dummy  = next(iter(train_loader))


model = AutoModelForQuestionAnswering.from_pretrained(model_checkpoint).to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr)

def train_step(model, optimizer, batch):
  model.train()

  optimizer.zero_grad()
  with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=use_amp):
    outputs = model(**batch)
    loss = outputs.loss

  scaler.scale(loss).backward()
  scaler.step(optimizer)
  scaler.update()

  return loss.item()

def evaluate_model(model, loader):
    model.eval()
    all_start, all_end = [], []
    with torch.inference_mode():
        for batch in loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=use_amp):
                outputs = model(**batch)
            all_start.append(outputs.start_logits.cpu().numpy())
            all_end.append(outputs.end_logits.cpu().numpy())
    return np.concatenate(all_start), np.concatenate(all_end)


train_loss_record = []
val_loss_record = []

if os.path.exists("./checkpoint.pt"):
  ckte = torch.load("./checkpoint.pt")
  model.load_state_dict(ckte["model"])
  optimizer.load_state_dict(ckte["optimizer"])
  scaler.load_state_dict(ckte["scaler"])
  epoch_start = ckte["epoch"] + 1  
  print("resuming from epooch ",epoch_start)
else:
  epoch_start = 0
  print("no checkpoint, starting fresh")
start_time = time.time()
for epoch in tqdm(range(epoch_start, args.epochs)):
  train_loss_batch = 0
  n = 0
  epoch_time_start = time.time()
  for batch in train_loader:
    batch = {k: v.to(device) for k, v in batch.items()}
    size = batch["input_ids"].shape[0]
    loss = train_step(model, optimizer, batch)
    train_loss_batch += loss *size
    n+= size
  epoch_time_end = time.time()
  train_loss_record.append(train_loss_batch / n)

  start_logits, end_logits = evaluate_model(model, val_loader)
  metrics = compute_metrics(start_logits, end_logits, validation_dataset, raw_datasets["validation"])

  print(f"===== Epoch {epoch}/{args.epochs-1} =====")
  print(f"Loss: {train_loss_record[-1]:.4f}") 
  print(f"Epoch {epoch} training time: {epoch_time_end - epoch_time_start:.2f} seconds")
  print(f"EM: {metrics['exact_match']:.4f}, F1: {metrics['f1']:.4f}")  

  if epoch%2 == 0 or epoch  == args.epochs - 1 :
   torch.save({"model": model.state_dict(), "epoch": epoch, "optimizer": optimizer.state_dict(), "scaler": scaler.state_dict()}, args.ckpt_path)
print(f"Total training time: {(time.time() - start_time):.2f} seconds")